import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

// DEFAULT METADATA WHEN IS NOT SETED EXPLICITLY IS default, and wen i seted, will be with template prefix Next.js 14 | (rest of page)
export const metadata = {
  title: {
    default: 'Next.js 14 default title',
    template: ' Next.js 14 | %s',
  },
  description: 'Generated by create next app desc',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
